name = "SpinQuantum"
uuid = "856139d4-bd2b-4127-8d9d-3972242b49a8"
authors = ["Goran Nakerst <go.nakerst@web.de>"]
version = "0.4.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
